### ISSUE TITLE
Scheduled Functions feature requests

### ISSUE THREAD

**Issue by swyxio** [netlify/functions#316]
Congrats on [launching Scheduled Functions](https://www.netlify.com/blog/quirrel-joins-netlify-and-scheduled-functions-launches-in-beta)!  i've been [working on a similar product](https://twitter.com/swyx/status/1475913498815528960?s=21) and thought I should note down immediate observations on features you may wish to add.

Feature menu for you to choose:

- Manual trigger in UI and in CLI - no need to write code to manual trigger
	- UI to backfill failed runs?
- Manual pause in UI and CLI
- View more than 1 next event in UI and in CLI
	- useful as sanity check in case user typed their cron syntax
	- basically anything doable via code should be available in UI and CLI and vice versa
- jitter start aka (+/- 100ms) - useful for bots, spreading out spikes
- set/update max # of invocations until schedule terminates itseld
- allow user to specify timezone, dont assume UTC
- "Last of" quartz scheduling syntax aka Last weekday of month, last Friday of month, see [cloudflare](https://developers.cloudflare.com/workers/platform/cron-triggers#supported-cron-expressions)
- holiday exclusion calendar
- ability to return value in function that will can be used in next invocation
	- beware overlapping schedules/background 
- context value or method to check amount of time until next invocation
- function that can update its own schedule

you should know how to reach me if you need clarification on any of these. and of course, no offense taken if all are rejected

**Comment by albertosantini** [comment]
> allow user to specify timezone, dont assume UTC

This ^ is very important for DSL. 
You need to be sure the job runs following the rules of a given timezone in terms of change of time.

Like in `cron` https://www.npmjs.com/package/cron

```
const weeklyJob = new CronJob("5 5 9 * * MON", () => {
    run();
}, null, false, "Europe/Rome");
```

**Comment by peroxy** [comment]
> Manual trigger in UI and in CLI - no need to write code to manual trigger

This is something I would love to have as well, especially for trying out the scheduled function during deploy previews.

**Comment by swyxio** [comment]
RIP

**Comment by swyxio** [comment]
still thinking of this
