### ISSUE TITLE
Consider moving to a 1.x.x release?

### ISSUE THREAD

**Issue by robations** [netlify/functions#317]
**Describe the bug**

Versions under a 0.x.x release imply a break in compatibility but no BC changes are listed in the changelog. (See [semver docs](https://semver.org/#spec-item-4)).

There are no BC breaks listed in the changelog — unclear if there aren't any or if they're just undocumented. When upgrading any 0.x.x version or major release, you want to understand how risky this process is in advance.

I would suggest to consider changing to a v1.x.x release which has better understood major/minor/bugfix semantics, especially given people are using this package (102,368 weekly downloads).

Thanks!

**Configuration**

N/a

**Pull requests**

This is more of a semantic/docs change but let me know if I can assist.

**Comment by eduardoboucas** [comment]
Hi @robations! We didn't have any recent breaking changes and we don't have any planned, so I agree we should move to a 1.0.0 version.

We'll keep this issue updated with any progress.

Thanks!
