### ISSUE TITLE
Publish edge functions runtime types

### ISSUE THREAD

**Issue by ascorbic** [netlify/functions#339]
The types for `Context` are currently only available in Deno. We should also publish them somewhere they can be consumed by Node.js code, and this package is probably the most sensible place. Feel free to move if needed!

**Comment by ericapisani** [comment]
Removing myself as the assignee as @netlify/compute team has [agreed to take this on](https://netlify.slack.com/archives/C0QFKKY2U/p1654335355909279?thread_ts=1654277088.219429&cid=C0QFKKY2U) 🎉

**Comment by nnelgxorz** [comment]
Hey everyone! Is there any updates on this? We would love to have properly sanctioned types for the Qwik City Netlify middleware! 😃

**Comment by jackiewmacharia** [comment]
Hey @nnelgxorz I'll work to get this wrapped up real soon!

**Comment by nnelgxorz** [comment]
Thanks @jackiewmacharia! You rock!

**Comment by jackiewmacharia** [comment]
Auto closed by PR completion, reopening till npm publishing is complete.

**Comment by nnelgxorz** [comment]
Awesome! Thanks again @jackiewmacharia!
