### ISSUE TITLE
`Handler` types incorrect for background functions

### ISSUE THREAD

**Issue by lucascaro** [netlify/functions#359]
**Describe the bug**

`Handler` types incorrect for background functions.

In the docs, there are many examples where a Handler function returns without a value. Additionally, the return value of a background function is irrelevant since they always return a 200 response.
But the type for `Handler` forces the function to return a `Response` which is confusing and somewhat misleading.

**Configuration**
@netlify/functions 1.2.0

**Comment by danez** [comment]
Will be solved with 1.3.0. There will be a new `BackgroundHandler` type.
