### ISSUE TITLE
Recommended way to import methods from local modules in production?

### ISSUE THREAD

**Issue by mrlubos** [netlify/functions#45]
Hey,

I have a Netlify function A located in `functions/netlify-a/netlify-a.js`. It relies on some method `b()` located in `functions/helpers/b.js`. This will work locally when running `netlify dev`, but won't work in production with the following message.

```js
{
  errorType: "Runtime.ImportModuleError",
  errorMessage: "Error: Cannot find module '../helpers'↵Require stack:↵- /var/task/netlify-a.js↵- /var/runtime/UserFunction.js↵- /var/runtime/index.js",
  trace: ["..."]
}
```

I understand that helpers are not bundled during the build time. What's the recommended way to fix this issue? I am already running `npm install` on every function folder to install `npm` dependencies, how would I go about importing helper methods without publishing them as a separate npm package?

Thanks!

**Comment by mrlubos** [comment]
Wonder if either one of you can help @sw-yx @DavidWells? Thank you!

**Comment by DavidWells** [comment]
@mrlubos just sent you an email on how to opt into the netlify build beta. There are new function bundling updates in there that might solve this resolution issue.

Please let me know if it works

**Comment by mrlubos** [comment]
Will do, thank you for the quick reply @DavidWells!

**Comment by mrlubos** [comment]
Hey @DavidWells, I tried the beta build and I can happily confirm it works! 🎉

Very surprising I haven't come across anyone else mentioning this as I'd expect more people running Netlify Dev reusing common code in their Netlify Functions. Oh well...

Btw, do you have any front-end roles available at Netlify? 🧐
