### ISSUE TITLE
Netlify Functions only work half of the time

### ISSUE THREAD

**Issue by winstonma** [netlify/functions#46]
To test my code, I forked your repo and added my own code ([Repo](https://github.com/winstonma/functions), with [my additional code](https://github.com/winstonma/functions/commit/4943baa9601fa5f2a613f24d01e8b86a039c212d)). I also deployed the code onto [Netlify](https://admiring-nobel-a43f4a.netlify.com/). The test is located at the bottom of the Netlify page. In short, I added 2 API and test code of the site.

When the code is tested locally both API works 100% of the time. But when the code is deployed the second API only work 50% of the time. When I run the full version it would give me the following error:

> {"error":"formats.find is not a function"}

Thanks for the help.

**Comment by DavidWells** [comment]
Sounds like `response.formats` is undefined or not an array here https://github.com/winstonma/functions/commit/4943baa9601fa5f2a613f24d01e8b86a039c212d#diff-ef15b8379e2c69cbf9fc5eb96c161ee3R12

Add a `console.log(response.formats)` and a check to verify that value exists before calling the `ytdl.chooseFormat` function

**Comment by winstonma** [comment]
Hi @DavidWells are there any caching behavior on the Netlify Server? If yes is it possible that I could disable this caching behavior?

**Comment by winstonma** [comment]
I closed this issue because the function is working after I updated the Javascript library.
