### ISSUE TITLE
`identity` type doesn't match docs

### ISSUE THREAD

**Issue by NotWoods** [netlify/functions#60]
**Describe the bug**

[This repo's typings](https://github.com/netlify/functions/blob/45c2ae3511a857459ff8985a6083ce31fa64aa7b/src/function/context.ts#L11) suggests that you access the Netlify Identity instance through `context.identity`, but the [Netlify docs](https://docs.netlify.com/functions/functions-and-identity/#access-identity-info-via-clientcontext) suggests its `context.clientContext.identity`.

**Configuration**

N/A

**Pull requests**

Let me know if this is correct or not. I can make a pull request to either move or copy the type.

**Comment by eduardoboucas** [comment]
The `identity` that you see in `context` is injected by AWS Lambda and refers to Amazon Cognito identity (see https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html).

Netlify Identity should be accessed via `context.clientContext.identity`, as stated in the docs. `clientContext` is currently just typed as `{ [key: string]: any }`.
