### ISSUE TITLE
[Bug] Fix wrong code url in ifttt-to-flick-instagram-make-new-github-post.md

### ISSUE THREAD

**Issue by D3AH** [netlify/functions#72]
The  code url is wrong in ifttt-to-flick-instagram-make-new-github-post.md function.  Returing a malformed url in the site: `https://github.com/https://github.com/rretsiem/renem.net/blob/574b1c5091e993b520e23f993a6c46069e92cdb0/src/functions`.

Should be set without domain to prevent that:
`rretsiem/renem.net/blob/574b1c5091e993b520e23f993a6c46069e92cdb0/src/functions`

**Comment by philhawksworth** [comment]
Fixed. Thanks for the sharp eyes, @D3AH !
