### ISSUE TITLE
[Typo] Small typo in options section of README.md 

### ISSUE THREAD

**Issue by tannerdolby** [netlify/functions#78]
Hello Netlify team, I noticed a small typo in the [options](https://github.com/netlify/functions#options) section. The third list item, should have "run" (or "start") added to it.

- `npm run debug` will the eleventy debugger

Should be updated to:

- `npm run debug` will run the eleventy debugger

Since it's such a small change I wasn't sure if I should submit a PR or not. I'm happy to fix it, just let me know.

**Comment by philhawksworth** [comment]
Thanks @tannerdolby! Fixed.

**Comment by tannerdolby** [comment]
Your welcome @philhawksworth! Marking this as closed now.
